### ISSUE TITLE
annotations/original-values.tailor.io causing invalid jsonpatch

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/tailor#112]
Error encountered when trying to run tailor update:
Update aborted: Error from server: jsonpatch replace operation does not apply: doc is missing path: /metadata/annotations/original-values.tailor.io~1spec.template.spec.containers.0.image

This happens if the annotation does not exist already in openshift

A workaround is to add that annotation in the yaml file:

```yaml
kind: DeploymentConfig
metadata:
  annotations:
    original-values.tailor.io/spec.template.spec.containers.0.image: 'sfc-dev/fe-angular-mvp:latest'
```

Error might be related in the content of the messages coming back and forth from OpenShift to/from client, as seen in: https://github.com/kubernetes/kubernetes/issues/63247
