### ISSUE TITLE
Export fails when no name is present

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#135]
E.g. `tailor export rolebinding -n foo-dev` might fail with:
```
2019/10/07 16:06:03 Could not export Kinds: [RoleBinding], Name: , Label: , ExcludedKinds: [], ExcludedNames: [], ExcludedLabels: [] resources as template: Could not parse object of exported template: Object has no key 'name'
```

The reason is that https://github.com/opendevstack/tailor/blob/1fff4cf5ca0f40f3b830edd02ff77fd2f45c2d2f/pkg/openshift/item.go#L124-L128 expects `/metadata/name` to exist, however some resources might not have it, e.g.:
```
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    generateName: system:image-pusher-
  roleRef:
    name: system:image-pusher
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: foo-dev
  userNames:
  - system:serviceaccount:foo-dev:default
```
