### ISSUE TITLE
The DeploymentConfig "be-python-flask" is invalid

### ISSUE THREAD

**Issue by henrjk** [opendevstack/tailor#145]
```bash
$ tailor version
0.10.2
```
On tailor update I get this message:

```
Patching dc/be-python-flask ... failed
2019/10/16 15:52:46 Update aborted: The DeploymentConfig "be-python-flask" is invalid: metadata.annotations: Invalid value: "tailor.opendevstack.org~1applied-config": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

dc/be-python-flask on the openshift web console contains (excerpt)
```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2019-07-15T08:55:30Z'
  generation: 10
  labels:
    app: asap
    branch: feature
    component: be-python-flask
    env: test
    template: component-template
  name: be-python-flask
  namespace: asap-test
  resourceVersion: '291686495'
...
```

When I introduce a dummy annotation like so in the web console a subsequent update works:

```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2019-07-15T08:55:30Z'
  generation: 10
  annotations:
    dummy: dummy
  labels:
...
```
Somewhat similar to #112
