### ISSUE TITLE
encrypted value without base64 encoding

### ISSUE THREAD

**Issue by henrjk** [opendevstack/tailor#148]
In this case I was aiming to have the following in a build config (excerpt)

```yaml
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
...
  spec:
...
    strategy:
      dockerStrategy:
        buildArgs:
        - name: nexusHostWithBasicAuth
          value: https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@${NEXUS_URL}
```
Now when I encrypt the NEXUS_PASSWORD with tailor secrets it will show up base64 encrypted in the template.
It appears I can work around this by instead defining NEXUS_PASSWORD.B64 in the encrypted file. 
However I think this is not as intended. So lets see whether this is a valid use case and if so how best to support it
