### ISSUE TITLE
tailor apply with wrong yaml leads to dump - v0.13 / 1.0 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/tailor#199]
1. create directory routet
1. yml below
```
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: test-route
    name: test-route
  spec:
    port:
      targetPort: 9000-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: sonarqube
      weight: 100
    wildcardPolicy: None
```
1. run tailor apply

utschig@WKS0000627058 MINGW64 /c/Temp/routet
$ tailor apply
2020/06/12 09:02:41 Fatal error: interface conversion: interface {} is []interface {}, not map[string]interface {} - goroutine 1 [running]:
runtime/debug.Stack(0xc000085590, 0x724ae0, 0xc0001d7350)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
main.main.func1()
        /Users/michaelsauter/dev/opendevstack/tailor/cmd/tailor/main.go:243 +0x5e
panic(0x724ae0, 0xc0001d7350)
        /usr/local/go/src/runtime/panic.go:679 +0x1c0
github.com/opendevstack/tailor/pkg/openshift.templateContainsTailorNamespaceParam(0xc00013c7c0, 0x10, 0xb, 0xc00013c7c0, 0x10)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/openshift/template.go:87 +0x471
github.com/opendevstack/tailor/pkg/openshift.ProcessTemplate(0x7797a5, 0x1, 0xc000142980, 0xe, 0x7797a5, 0x1, 0xc000194000, 0x25f0008, 0xc000140050, 0x0, ...)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/openshift/template.go:29 +0x2af
github.com/opendevstack/tailor/pkg/commands.assembleTemplateBasedResourceList(0xc00023e000, 0xc000194000, 0x25f0008, 0xc000140050, 0xc000140050, 0x0, 0xc00023e000)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/commands/diff.go:186 +0x3a4
github.com/opendevstack/tailor/pkg/commands.calculateChangeset(0x7e3460, 0xc0001d69f0, 0xc000194000, 0x7e6040, 0xc000140050, 0x58900d, 0xc000085c78, 0x1, 0x1)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/commands/diff.go:60 +0x227
github.com/opendevstack/tailor/pkg/commands.Apply(0xc000046400, 0xc000194000, 0x8, 0x0, 0x0)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/commands/apply.go:17 +0xdd
main.main()
        /Users/michaelsauter/dev/opendevstack/tailor/cmd/tailor/main.go:406 +0xa93
.
