### ISSUE TITLE
Feature: to import deployment autoscaling configuration

### ISSUE THREAD

**Issue by jssnull** [opendevstack/tailor#226]
Hi,
I think that would be very useful to implement the possibility to import the autoscaling configuration of a Deployment.

That kind of configuration should follow a format like this:

```yaml
apiVersion: autoscaling.openshift.io/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: my-app
    template: component-template
  name: my-app-name
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1 
    kind: DeploymentConfig 
    name: my-app
    subresource: scale
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 40
```

here is the related OCP docs: https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html

Would be possible to implement this feature on tailor?

Best Regards
