### ISSUE TITLE
Add possibility to decode base64 encoded parameters that are needed in clear text

### ISSUE THREAD

**Issue by henninggross** [opendevstack/tailor#236]
# Issue
There are cases where one needs to have a multiline value (e.g. a certificate or a RSA key) in their template in clear text.

See this example (where `TLS_CERTIFICATE` and `TLS_PRIVATE_KEY` should be multiline values):
```yaml
- apiVersion: route.openshift.io/v1
 kind: Route
...
 tls:
    certificate: ${TLS_CERTIFICATE}
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
    key: ${TLS_PRIVATE_KEY}
```

When one now wants to add a key or a certificate to his `.env.enc` file he needs to base64 encode them and add a suffix to the parameter like this:
`TLS_CERTIFICATE.B64=BASE_64_ENCODED_VALUE`

This results in Tailor adding the base64 encoded value to the OpenShift template, which is not what one wants to happen with such parameters.

# Possible Solution
A possible solution might be to introduce a suffix like `.B64DECODE` that tells Tailor to take the base64 encoded value and decode it before adding it to the template.
